### ISSUE TITLE
  undefined method `vault' for Chef::Resource::User

### ISSUE THREAD

**Issue by katmai** [Nordstrom/chef-vault#170]
Hi,

I tried googling for this but didn't find any info. So i made a cookbook to test creating a user which password is taken from the vault:

```
chef_gem 'chef-vault' do
  compile_time true if respond_to?(:compile_time)
end

require 'chef-vault'

item = ChefVault::Item.load("passwords", "vaultuser")
item["password"]

user "vaultuser" do
  password vault['vaultuser']
  home "/home/vaultuser"
  supports :manage_home => true
  shell "/bin/bash"
  comment "Chef Vault User"
end
```

The result i am getting is:
```
root@tcs-02B89C:/etc/chef# chef-client
Starting Chef Client, version 12.3.0
resolving cookbooks for run list: ["motd::cow", "vault"]
Synchronizing Cookbooks:
  - motd
  - chef_handler
  - vault
Compiling Cookbooks...
Recipe: vault::default
  * chef_gem[chef-vault] action install (up to date)

  ================================================================================
  Recipe Compile Error in /var/chef/cache/cookbooks/vault/recipes/default.rb
  ================================================================================

  NoMethodError
  -------------
  undefined method `vault' for Chef::Resource::User

  Cookbook Trace:
  ---------------
    /var/chef/cache/cookbooks/vault/recipes/default.rb:19:in `block in from_file'
    /var/chef/cache/cookbooks/vault/recipes/default.rb:18:in `from_file'

  Relevant File Content:
  ----------------------
  /var/chef/cache/cookbooks/vault/recipes/default.rb:

   12:
   13:  require 'chef-vault'
   14:
   15:  item = ChefVault::Item.load("passwords", "vaultuser")
   16:  item["password"]
   17:
   18:  user "vaultuser" do
   19>>   password vault['vaultuser']
   20:    home "/home/vaultuser"
   21:    supports :manage_home => true
   22:    shell "/bin/bash"
   23:    comment "Chef Vault User"
   24:  end
   25:


  Running handlers:
[2015-05-27T09:05:24+00:00] ERROR: Running exception handlers
  Running handlers complete
[2015-05-27T09:05:24+00:00] ERROR: Exception handlers complete
[2015-05-27T09:05:24+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
  Chef Client failed. 0 resources updated in 29.456716751 seconds
[2015-05-27T09:05:25+00:00] ERROR: undefined method `vault' for Chef::Resource::User
[2015-05-27T09:05:26+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

```

Am i doing something wrong?

Thanks for the help.

**Comment by katmai** [comment]
i r stoopid. for some reason i was calling it vault. when the password was called "item"
